# Generated by Django 5.0.7 on 2024-12-10 12:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zaala Society', help_text='Application name', max_length=100)),
                ('short_name', models.CharField(default='ZS', help_text='Your application short name', max_length=10)),
                ('tagline', models.CharField(default='will be update it soon', help_text='Your application business line', max_length=100)),
                ('description', models.TextField(default='will be update it soon', help_text='Application description')),
                ('favicon', models.ImageField(blank=True, help_text='Application favicon', null=True, upload_to='core/application/images')),
                ('logo', models.ImageField(blank=True, help_text='Application real colors logo', null=True, upload_to='core/application/images')),
                ('logo_dark', models.ImageField(blank=True, help_text='For dark theme only', null=True, upload_to='core/application/images')),
                ('logo_light', models.ImageField(blank=True, help_text='For light theme only', null=True, upload_to='core/application/images')),
                ('contact_email1', models.EmailField(default='support@zaalasociety.com', help_text='Application contact email 1', max_length=100)),
                ('contact_email2', models.EmailField(default='support@zaalasociety.com', help_text='Application contact email 2', max_length=100)),
                ('contact_phone1', phonenumber_field.modelfields.PhoneNumberField(default='+923029677678', help_text='Application contact phone 1', max_length=128, region=None)),
                ('contact_phone2', phonenumber_field.modelfields.PhoneNumberField(default='+923065953957', help_text='Application contact phone 2', max_length=128, region=None)),
                ('address', models.CharField(default='Mandian Abbottabad Near Comsats University', help_text='office address', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=23.7, help_text='latitude', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=90.3, help_text='longitude', max_digits=10)),
                ('terms_url', models.URLField(default='https://zaalasociety.com/terms-of-use/', help_text='Terms and Conditions page link', max_length=255)),
                ('version', models.CharField(default='1.0.0', help_text='Current version', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Application',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Full Name', max_length=50)),
                ('subject', models.CharField(help_text='Message Subject', max_length=100)),
                ('message', models.TextField(help_text='Your Message', max_length=1000)),
                ('email', models.EmailField(help_text='Your Email Address', max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Your Contact Number', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True)),
                ('language', models.CharField(blank=True, default='en', help_text='ISO 639-1', max_length=3, null=True)),
                ('currency', models.CharField(blank=True, default='USD', help_text='ISO 4217', max_length=3, null=True)),
                ('phone_code', models.CharField(blank=True, default='+1', help_text='e.g. +1', max_length=4, null=True)),
                ('is_services_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('role', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
